# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import person_pb2 as person__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\005proto'),
  serialized_pb=_b('\n\rservice.proto\x1a\x0cperson.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x10getPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x96\x01\n\x05HuaFu\x12)\n\tGetPerson\x12\x11.getPersonRequest\x1a\x07.Person\"\x00\x12/\n\x0bQueryPerson\x12\x11.getPersonRequest\x1a\x07.Person\"\x00(\x01\x30\x01\x12\x31\n\nListPeople\x12\x16.google.protobuf.Empty\x1a\x07.Person\"\x00\x30\x01\x42\x07Z\x05protob\x06proto3')
  ,
  dependencies=[person__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GETPERSONREQUEST = _descriptor.Descriptor(
  name='getPersonRequest',
  full_name='getPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='getPersonRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['getPersonRequest'] = _GETPERSONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

getPersonRequest = _reflection.GeneratedProtocolMessageType('getPersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPERSONREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:getPersonRequest)
  ))
_sym_db.RegisterMessage(getPersonRequest)


DESCRIPTOR._options = None

_HUAFU = _descriptor.ServiceDescriptor(
  name='HuaFu',
  full_name='HuaFu',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=243,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPerson',
    full_name='HuaFu.GetPerson',
    index=0,
    containing_service=None,
    input_type=_GETPERSONREQUEST,
    output_type=person__pb2._PERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryPerson',
    full_name='HuaFu.QueryPerson',
    index=1,
    containing_service=None,
    input_type=_GETPERSONREQUEST,
    output_type=person__pb2._PERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPeople',
    full_name='HuaFu.ListPeople',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=person__pb2._PERSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUAFU)

DESCRIPTOR.services_by_name['HuaFu'] = _HUAFU

# @@protoc_insertion_point(module_scope)
