# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import person_pb2 as person__pb2
from . import service_pb2 as service__pb2


class HuaFuStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPerson = channel.unary_unary(
        '/HuaFu/GetPerson',
        request_serializer=service__pb2.getPersonRequest.SerializeToString,
        response_deserializer=person__pb2.Person.FromString,
        )
    self.QueryPerson = channel.stream_stream(
        '/HuaFu/QueryPerson',
        request_serializer=service__pb2.getPersonRequest.SerializeToString,
        response_deserializer=person__pb2.Person.FromString,
        )
    self.ListPeople = channel.unary_stream(
        '/HuaFu/ListPeople',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=person__pb2.Person.FromString,
        )


class HuaFuServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryPerson(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPeople(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HuaFuServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPerson': grpc.unary_unary_rpc_method_handler(
          servicer.GetPerson,
          request_deserializer=service__pb2.getPersonRequest.FromString,
          response_serializer=person__pb2.Person.SerializeToString,
      ),
      'QueryPerson': grpc.stream_stream_rpc_method_handler(
          servicer.QueryPerson,
          request_deserializer=service__pb2.getPersonRequest.FromString,
          response_serializer=person__pb2.Person.SerializeToString,
      ),
      'ListPeople': grpc.unary_stream_rpc_method_handler(
          servicer.ListPeople,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=person__pb2.Person.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HuaFu', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
